CUSTOM_TEMPLATES = {
    "oxford_pets": "a type of pet, a photo of a {}.",
    "oxford_flowers": "a type of flower, a photo of a {}.",
    "fgvc_aircraft": "a type of aircraft, a photo of a {}.",
    "dtd": "a texture of {}.",
    "eurosat": "a centered satellite photo of {}.",
    "stanford_cars": "a photo of a {}.",
    "food101": "a type of food, a photo of {}.",
    "sun397": "a photo of a {}.",
    "caltech101": "a photo of a {}.",
    "ucf": "a photo of a person doing {}.",
    "imagenet": "a photo of a {}.",
    "imagenet_s": "a photo of a {}.",
    "imagenetv2": "a photo of a {}.",
    "imagenet_a": "a photo of a {}.",
    "imagenet_r": "a photo of a {}.",
    "imagenet_s": "a photo of a {}.",
    "domain_net": "a photo of a {}.",
    "tiny_imagenet": "a photo of a {}.",
    "inaturalist": "a photo of a {}.",
}